version: "3.8"
services:
  austrian_dsmr_mqtt:
    image: austrian_dsmr_mqtt
    container_name: austrian_dsmr_mqtt
    network_mode: hassio
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      GUEK: "myGUEK"
      GAK: "myGAK"
      MQTT_BROKER: "mybroker"
      MQTT_USER: "myuser"
      MQTT_PASSWORD: "mypassword"
      SERIAL_INPUT_PORT: "/dev/ttyUSB0"
    restart: always
